version: 2
updates:
  # Gradle dependencies
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "@timhubert"
    assignees:
      - "@timhubert"
    commit-message:
      prefix: "build"
      include: "scope"
    
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "@timhubert"
    assignees:
      - "@timhubert"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "@timhubert"
    assignees:
      - "@timhubert"
    commit-message:
      prefix: "docker"
      include: "scope"
