version: "1"
services:
  - type: web
    name: gymtracker-backend
    env: docker
    dockerfilePath: ./dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: JAVA_OPTS
        value: "-Xmx512m -Xms256m"
    healthCheckPath: /actuator/health
    autoDeploy: true
    branch: main
