name: Deploy to Production

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build application
      run: ./gradlew build
      
    - name: Build Docker image
      run: |
        docker build -t gymtracker:${{ github.sha }} .
        docker tag gymtracker:${{ github.sha }} gymtracker:latest
        
    # Hier können Sie weitere Deployment-Schritte hinzufügen:
    # - Push zu Docker Registry
    # - Deploy zu Cloud Provider (Heroku, AWS, etc.)
    # - Deploy zu eigenem Server via SSH
    
    - name: Deploy notification
      run: echo "Deployment completed for commit ${{ github.sha }}"
